### ISSUE TITLE
Make saved URNs panel draggable

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ict2#10]
Now that we're using a fancy css framework, we should consider making the saved-urn/preview panel draggable and collapsable, so we can get it entirely out of the way if we want.

**Comment by MGelein** [comment]
Collapsable is no problem (already did the same thing with the settings panel). I'm not too sure how to go about making it draggable yet.

**Comment by MGelein** [comment]
The panel is now collapsable 

edit: Assuming the pull request gets approved

**Comment by Eumaeus** [comment]
Resolved by Mees.
