### ISSUE TITLE
Make it easy  to grab a binrary image of an ROI, at full-rez

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ict2#17]
Wrap the preview image in a variant URL that opens a binary image at full resolution.

**Comment by MGelein** [comment]
I already have working source code for this. You can see it in action [here](http://www.interwing.nl/hmt/img/)
If you want I can implement this in 5 minutes tomorrow morning.

**Comment by Eumaeus** [comment]
Done. Clicking on the preview image now takes you to a full-rez binary.
