### ISSUE TITLE
First URN in the URL variables is parsed twice

### ISSUE THREAD

**Issue by MGelein** [cite-architecture/ict2#19]
When you go to [this page](http://www.homermultitext.org/ict2/?urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.2024,0.3610,0.008400,0.04587&urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.2173,0.3131,0.1684,0.06508)
You should see two ROI's but the first ROI is added twice.

**Comment by Eumaeus** [comment]
Thanks! I'll get in this.

**Comment by Eumaeus** [comment]
Fixed.
