### ISSUE TITLE
Curious Behavior by the Citation Tool

### ISSUE THREAD

**Issue by zachsowerby** [cite-architecture/ict2#3]
It appears that, if when drawing boxes using this tool, the urn data for the 24th box becomes duplicated in the sidebar, and not assigned/referencing a box on the image. This can make the counting of 24+ citations at a time off by 1.

**Comment by Eumaeus** [comment]
Thanks, Zach. I'm not surprised by this. I will not be able to look at it today (Thursday), but I will make this a priority.

**Comment by Eumaeus** [comment]
Fixed. Easy fix… off by one, plus missing on CSS selector.

**Comment by Eumaeus** [comment]
(Fixed version uploaded to homermultitext.org, and briefly tested.)
